target 'iosApp' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crashlytics'
  pod 'utils', :path => '../shared/utils'
  pod 'data', :path => '../shared/data'
  pod 'domain', :path => '../shared/domain'
end