target 'iosApp' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crashlytics'
  pod 'client', :path => '../shared/client'
end