default_platform(:android)

platform :android do

    desc "Lane for distributing app using Firebase App Distributions"
    lane :distribute do
        gradle(task: "clean assembleDebug")
        firebase_app_distribution(
            service_credentials_file: "firebase_credentials.json",
            app: ENV['FAD_ANDROID_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups: "all"
        )
    end

end